version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    container_name: foodgram_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: itslight/foodgram_backend
    container_name: foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: itslight/foodgram_frontend
    container_name: foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    image: itslight/foodgram_nginx
    container_name: foodgram_nginx
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
    ports:
      - 9090:80