# Generated by Django 3.2 on 2023-04-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name'], 'verbose_name': 'произведение', 'verbose_name_plural': 'произведения'},
        ),
    ]
