# Generated by Django 3.2 on 2023-04-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_title_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name'], 'verbose_name': 'произведение', 'verbose_name_plural': 'произведения'},
        ),
    ]
